definitions: {}
info:
  contact:
    email: cdis@uchicago.edu
  description: A service template for CDIS Gen 3 data commons. Code is available on
    [GitHub](https://github.com/uc-cdis/template-repo).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://cdis.uchicago.edu/terms/
  title: Service template OpenAPI Specification
  version: '1.0'
paths:
  /_status:
    get:
      responses:
        '200':
          description: Healthy
        default:
          description: Unhealthy
      summary: Health check endpoint
      tags:
      - system
swagger: '2.0'
